torch.mm

torch.bmm

torch.matmul

torch.dot

'*' 연산

In [1]:
import math
import torch
import torch.nn as nn
import torch.nn.functional as F

# '*' 연산

In [9]:
position = torch.arange(0, 10).unsqueeze(1)
print(position.shape)
#print(position)
div_term = torch.FloatTensor(2)
print(div_term.shape)
c = position * div_term
print(c.shape)
c

torch.Size([10, 1])
torch.Size([2])
torch.Size([10, 2])


tensor([[-0.0000e+00,  0.0000e+00],
        [-8.5910e-07,  3.0721e-41],
        [-1.7182e-06,  6.1441e-41],
        [-2.5773e-06,  9.2162e-41],
        [-3.4364e-06,  1.2288e-40],
        [-4.2955e-06,  1.5360e-40],
        [-5.1546e-06,  1.8432e-40],
        [-6.0137e-06,  2.1504e-40],
        [-6.8728e-06,  2.4577e-40],
        [-7.7319e-06,  2.7649e-40]])

In [ ]:
x = torch.FloatTensor(30, 16, 5

# torch.mm

mm은 matrix multiplication으로, [n, m] x [m,p] = [n,p] 를 구현한다.

torch.matmul과 차이점은 broadcast가 안 된다는 점이다.

dim 무조건 맞춰야 됨!!!


In [16]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.mm(mat1, mat2)

tensor([[ 0.0623, -1.6126, -0.1580],
        [-4.3794,  2.3617,  0.7619]])

# torch.bmm

broadcast 지원 x

input and mat2 must be 3-D tensors each containing the same number of matrices.

In [14]:
#입력 2개의 batch size가 동일해야지만 가능!
batchsize = 5
mat1 = torch.randn(batchsize, 2, 3)
mat2 = torch.randn(batchsize, 3, 3)
torch.bmm(mat1, mat2)

tensor([[[ 4.2251,  2.4575, -3.3912],
         [ 0.4659,  1.1431, -2.1906]],

        [[-0.6381,  0.0573,  1.8721],
         [ 0.7174,  1.4686,  2.4662]],

        [[-0.3745, -0.1837, -1.2885],
         [-1.7367,  4.2769,  0.2947]],

        [[-1.6734,  2.5337, -2.6090],
         [-3.2169, -0.5292,  1.7518]],

        [[ 1.2480, -1.6275, -0.5711],
         [ 0.8394, -1.5739,  2.7863]]])

# torch.matmul

In [17]:
# both tensors are 1-dimensional, the dot product (scalar) is returned.

a = torch.randn(10)
b = torch.randn(10)
torch.matmul(a,b)

tensor(-6.2479)

--------------------------------------

In [21]:
# both arguments are 2-dimensional, the matrix-matrix product is returned.

mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.matmul(mat1, mat2)

tensor([[-4.0483, -0.6575, -1.9530],
        [ 0.2225,  0.2905, -0.0356]])

-------------------------------

In [38]:
# first : 1 dimensional
# second : 2 dimensional

mat1 = torch.FloatTensor([0,1,2])
#mat1 = torch.randn(3)
print("mat1 : ", mat1.shape, "\n", mat1, '\n')

mat2 = torch.randn(3, 3)
print("mat1 : ", mat2.shape, "\n", mat2, '\n')

print("----------결과-------")
torch.matmul(mat1, mat2)

mat1 :  torch.Size([3]) 
 tensor([0., 1., 2.]) 

mat1 :  torch.Size([3, 3]) 
 tensor([[-0.1570,  1.2064,  0.7127],
        [-1.1103,  2.0451, -0.1634],
        [-1.6100,  1.2194,  1.1063]]) 

----------결과-------


tensor([-4.3303,  4.4840,  2.0493])

-----------------

In [52]:
# first : 2 dimensional
# second : 1 dimensional

mat1 = torch.FloatTensor([[1,2,3, 4],[5,6, 7, 8], [9, 10, 11, 12]])
print("mat1 : ", mat1.shape, "\n", mat1, '\n')
mat2 = torch.FloatTensor([0, 1 ,2, 4])
print("mat1 : ", mat2.shape, "\n", mat2, '\n')
print("----------결과-------")
torch.matmul(mat1, mat2)

mat1 :  torch.Size([3, 4]) 
 tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) 

mat1 :  torch.Size([4]) 
 tensor([0., 1., 2., 4.]) 

----------결과-------


tensor([24., 52., 80.])

In [49]:
# matrix x vector 위에랑 같은 거!
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([3])

In [64]:
tensor1 = torch.randn(10, 1)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

RuntimeError: ignored

-------

In [53]:
# batched matrix x broadcasted vector
>>> tensor1 = torch.randn(10, 3, 4)
>>> tensor2 = torch.randn(4)
>>> torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3])

------------------

In [54]:
# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

-----------------

In [55]:
# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

------------

In [57]:
# [ j x 1 x n x n]           [k x n x n]
# output : [j x k x n x n]
tensor1 = torch.randn(10, 1, 4, 4)
tensor2 = torch.randn(7, 4, 4)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 7, 4, 4])

--------------

In [65]:
# [j x 1 x n x m]
# [k x m x p]
# output : [j x k x n x p]
tensor1 = torch.randn(10, 1, 5, 6)
tensor2 = torch.randn(4, 6, 9)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 4, 5, 9])

# Tensor  생성

In [46]:
x = torch.IntTensor([[1,2,3],[4,5,6], [7, 8, 9]])    #FloatTensor
print(x.shape)
x

torch.Size([3, 3])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)